user:
  name: "Bhanu Reddy"
  location: "Bengaluru,IN"   # for weather API

ui:
  layout: at_a_glance
  min_width: 100
  tile_height: 7

widgets:
  weather:
    ttl: 600s
    api_key: "YOUR_OWM_API_KEY"
  news:
    ttl: 600s
    tags: [golang, security, ai]
    provider: hn        # hn | devto | newsapi
  slack:
    ttl: 20s
  confluence:
    ttl: 300s
  jira:
    ttl: 45s
    log_work: true
  traffic:
    ttl: 300s  # 5 minutes refresh
    # Option 1: Try with coordinates for reliability
    origin:
      latitude: 12.938073302563163
      longitude: 77.7124699619538
      name: "HOME"
    destination:
      latitude: 12.924750670796934
      longitude: 77.67027589768634
      name: "OFFICE"
    
    # Option 2: Alternative addresses (uncomment to use)
    # origin: "Panathur, Bengaluru, Karnataka, India"
    # destination: "Bellandur, Bengaluru, Karnataka, India"
  calendar:
    ttl: 300s  # 5 minutes refresh
    max_events: 10
    days_ahead: 7
    # credentials_file and token_file will be auto-set to ~/.goday/
